version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: job-agent-postgres-dev
    environment:
      POSTGRES_DB: job_agent_db
      POSTGRES_USER: job_agent_user
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - job-agent-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: job-agent-redis-dev
    ports:
      - "6379:6379"
    networks:
      - job-agent-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: job-agent-backend-dev
    environment:
      - DATABASE_URL=postgresql://job_agent_user:postgres@postgres:5432/job_agent_db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
      - SECRET_KEY=dev-secret-key-change-in-production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ENVIRONMENT=development
      - DEBUG=true
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
    networks:
      - job-agent-network
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: job-agent-frontend-dev
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api/v1
      - VITE_APP_NAME=Job Agent System
      - VITE_APP_VERSION=1.0.0
      - VITE_ENABLE_DEBUG=true
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - job-agent-network
    command: npm run dev

  # Celery Worker (optional for development)
  celery-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: job-agent-celery-worker-dev
    command: celery -A app.core.celery worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql://job_agent_user:postgres@postgres:5432/job_agent_db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/1
      - CELERY_RESULT_BACKEND=redis://redis:6379/2
      - SECRET_KEY=dev-secret-key-change-in-production
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ENVIRONMENT=development
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend:/app
      - ./uploads:/app/uploads
    networks:
      - job-agent-network
    profiles:
      - celery

volumes:
  postgres_data:
    driver: local

networks:
  job-agent-network:
    driver: bridge